---
- name: myapp - install python requirements
  pip:
    name: "{{ python_requirements }}"
    executable: pip3

- name: myapp - deploy application
  template:
    src: templates/myapp.py.j2
    dest: /usr/share/myapp.py
    mode: 0777

- name: myapp - confugure service
  template:
    src: templates/myapp.service.j2
    dest: /lib/systemd/system/myapp.service
  notify:
    myapp - restart
